# Generated by Django 4.0.2 on 2022-03-10 08:23

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("consvc_shepherd", "0001_squashed_0004_advertiserurl_geo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertiserurl",
            name="exact",
        ),
        migrations.RemoveField(
            model_name="advertiserurl",
            name="prefix",
        ),
        migrations.AddField(
            model_name="advertiserurl",
            name="matching",
            field=models.BooleanField(
                choices=[(True, "exact"), (False, "prefix")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="advertiserurl",
            name="geo",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="advertiserurl",
            name="path",
            field=models.CharField(max_length=128),
        ),
    ]
