# Generated by Django 4.0.2 on 2022-03-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("consvc_shepherd", "0002_alter_advertiserurl_domain"),
        ("consvc_shepherd", "0003_alter_advertiserurl_domain"),
    ]

    dependencies = [
        ("consvc_shepherd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertiserurl",
            name="domain",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="advertiserurl",
            name="domain",
            field=models.CharField(max_length=253),
        ),
    ]
