# Generated by Django 4.0.2 on 2022-03-16 07:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("consvc_shepherd", "0002_alter_partner_click_hosts_and_more"),
        ("consvc_shepherd", "0003_alter_partner_click_hosts_and_more"),
    ]

    dependencies = [
        ("consvc_shepherd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="click_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="impression_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128, null=True),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="click_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128, null=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="impression_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=128, null=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
