# Generated by Django 4.0.2 on 2022-03-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0002_alter_advertiserurl_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingssnapshot",
            name="settings_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="consvc_shepherd.partner",
            ),
        ),
    ]
