# Generated by Django 4.0.2 on 2022-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0002_alter_advertiserurl_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertiserurl",
            name="domain",
            field=models.CharField(max_length=253),
        ),
    ]
