# Generated by Django 4.0.2 on 2022-03-16 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "consvc_shepherd",
            "0002_alter_partner_click_hosts_alter_partner_click_hosts_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PartnerAdUrl",
        ),
    ]
