# Generated by Django 4.0.2 on 2022-03-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ("consvc_shepherd", "0002_remove_advertiserurl_exact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingssnapshot",
            name="launched_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="settingssnapshot",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
