# Generated by Django 4.0.2 on 2022-03-12 01:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0003_settingssnapshot_launched_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertiserurl",
            name="click_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="advertiserurl",
            name="impression_hosts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="advertiserurl",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
