# Generated by Django 4.0.2 on 2022-04-04 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0001_initial"),
        ("consvc_shepherd", "0003_settingssnapshot_settings_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertiserurl",
            name="advertiser",
        ),
        migrations.AlterField(
            model_name="settingssnapshot",
            name="settings_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contile.partner",
            ),
        ),
        migrations.DeleteModel(
            name="Advertiser",
        ),
        migrations.DeleteModel(
            name="AdvertiserUrl",
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
    ]
