# Generated by Django 4.1.7 on 2023-04-24 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0005_remove_partner_click_hosts_and_more"),
        ("consvc_shepherd", "0004_remove_advertiserurl_advertiser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartnerAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.IntegerField()),
                (
                    "allocationPosition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_allocations",
                        to="consvc_shepherd.allocationsetting",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contile.partner",
                    ),
                ),
            ],
        ),
    ]
