# Generated by Django 4.2.1 on 2023-05-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0005_allocationsetting_partnerallocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partnerallocation",
            old_name="allocationPosition",
            new_name="allocation_position",
        ),
    ]
