# Generated by Django 4.2.1 on 2023-06-20 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0005_remove_partner_click_hosts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "consvc_shepherd",
            "0006_rename_allocationposition_partnerallocation_allocation_position",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerallocation",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contile.partner",
            ),
        ),
        migrations.AlterField(
            model_name="settingssnapshot",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ss_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="settingssnapshot",
            name="launched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ss_launched_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AllocationSettingsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("json_settings", models.JSONField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("launched_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alloc_ss_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "launched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alloc_ss_launched_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
