# Generated by Django 4.2.1 on 2023-07-10 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0007_alter_partnerallocation_partner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerallocation",
            name="percentage",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
