# Generated by Django 4.2.14 on 2024-07-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0007_alter_partnerallocation_partner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostrDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boostr_id", models.IntegerField(unique=True)),
                ("name", models.CharField()),
                ("advertiser", models.CharField()),
                ("currency", models.CharField()),
                ("amount", models.IntegerField()),
                ("sales_representatives", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BoostrProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boostr_id", models.IntegerField(unique=True)),
                ("full_name", models.CharField()),
                ("campaign_type", models.CharField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BoostrDealProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.IntegerField()),
                ("month", models.CharField()),
                (
                    "boostr_deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.boostrdeal",
                    ),
                ),
                (
                    "boostr_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.boostrproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="boostrdeal",
            name="products",
            field=models.ManyToManyField(
                related_name="products",
                through="consvc_shepherd.BoostrDealProduct",
                to="consvc_shepherd.boostrproduct",
            ),
        ),
    ]
