# Generated by Django 4.2.13 on 2024-07-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0007_alter_partnerallocation_partner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostrDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boostr_id", models.IntegerField()),
                ("name", models.CharField(max_length=128)),
                ("advertiser", models.CharField(max_length=128)),
                ("currency", models.CharField()),
                ("amount", models.IntegerField()),
                ("sales_representatives", models.CharField(max_length=128)),
                ("campaign_type", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BoostrProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boostr_id", models.IntegerField()),
                ("name", models.CharField(max_length=128)),
                ("campaign_type", models.CharField()),
                ("country_code", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.boostrdeal",
                    ),
                ),
            ],
        ),
    ]
