# Generated by Django 4.2.14 on 2024-07-30 01:03

from django.db import migrations

CREATE_SQL = """
CREATE OR REPLACE VIEW revenue_overview AS
SELECT
row_number() OVER () as id,
full_name AS placement,
sum(amount) AS budget,
sum(amount) - SUM(budget) AS revenue_delta,
consvc_shepherd_boostrdealproduct.month
FROM
consvc_shepherd_boostrdealproduct
LEFT JOIN consvc_shepherd_boostrproduct ON consvc_shepherd_boostrdealproduct.boostr_product_id =
 consvc_shepherd_boostrproduct.id
LEFT JOIN consvc_shepherd_boostrdeal ON consvc_shepherd_boostrdealproduct.boostr_deal_id =
 consvc_shepherd_boostrdeal.id
GROUP BY
full_name,
consvc_shepherd_boostrdealproduct.month
ORDER BY
MONTH ASC,
full_name ASC
"""

DROP_SQL = "DROP VIEW IF EXISTS revenue_overview;"


class Migration(migrations.Migration):
    dependencies = [
        ("consvc_shepherd", "0008_boostrdeal_boostrproduct_boostrdealproduct_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
