# Generated by Django 4.2.14 on 2024-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0008_boostrdeal_boostrproduct_boostrdealproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boostrproduct",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("CPC", "Cpc"),
                    ("CPM", "Cpm"),
                    ("Flat Fee", "Flat Fee"),
                    ("None", "None"),
                ]
            ),
        ),
    ]
