# Generated by Django 4.2.14 on 2024-07-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0009_alter_boostrproduct_campaign_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostrSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced_on", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField()),
                ("message", models.CharField()),
            ],
        ),
    ]
