# Generated by Django 4.2.14 on 2024-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0009_alter_boostrproduct_campaign_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoostrSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synced_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failure", "Failure")]
                    ),
                ),
                ("message", models.CharField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
