# Generated by Django 4.2.14 on 2024-09-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0009_alter_boostrproduct_campaign_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="boostrproduct",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("DE", "Germany"),
                    ("ES", "Spain"),
                    ("FR", "France"),
                    ("GB", "United Kingdom"),
                    ("IT", "Italy"),
                    ("PL", "Poland"),
                    ("AT", "Austria"),
                    ("NL", "Netherlands"),
                    ("LU", "Luxembourg"),
                    ("CH", "Switzerland"),
                    ("BE", "Belgium"),
                ],
            ),
        ),
    ]
