# Generated by Django 4.2.14 on 2024-08-02 02:01

import consvc_shepherd.models
import datetime
from django.db import migrations, models
import django.db.models.deletion

CREATE_SQL = """
CREATE OR REPLACE VIEW revenue_overview AS
SELECT
row_number() OVER () as id,
full_name AS placement,
sum(amount) AS budget,
sum(amount) - SUM(budget) AS revenue_delta,
consvc_shepherd_boostrdealproduct.month
FROM
consvc_shepherd_boostrdealproduct
LEFT JOIN consvc_shepherd_boostrproduct ON consvc_shepherd_boostrdealproduct.boostr_product_id =
 consvc_shepherd_boostrproduct.id
LEFT JOIN consvc_shepherd_boostrdeal ON consvc_shepherd_boostrdealproduct.boostr_deal_id =
 consvc_shepherd_boostrdeal.id
GROUP BY
full_name,
consvc_shepherd_boostrdealproduct.month
ORDER BY
MONTH ASC,
full_name ASC
"""

DROP_SQL = "DROP VIEW IF EXISTS revenue_overview;"


class Migration(migrations.Migration):
    dependencies = [
        ("consvc_shepherd", "0009_revenue_overview_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placement", models.CharField()),
                ("revenue", models.IntegerField()),
                ("budget", models.IntegerField()),
                ("revenue_delta", models.IntegerField()),
                ("month", models.DateField()),
            ],
            options={
                "db_table": "revenue_overview",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(default="US", max_length=100)),
            ],
        ),
        migrations.RunSQL(
            sql=DROP_SQL,
            reverse_sql=CREATE_SQL,
        ),
        migrations.AlterField(
            model_name="boostrdealproduct",
            name="month",
            field=models.DateField(),
        ),
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
        migrations.CreateModel(
            name="AdsInventoryForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Month & Year"
                    ),
                ),
                ("forecast", models.IntegerField(default=10)),
                (
                    "country",
                    models.ForeignKey(
                        default=consvc_shepherd.models.Country.get_default_country,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.countries",
                    ),
                ),
            ],
            options={
                "ordering": ["month", "country__code"],
            },
        ),
    ]
