# Generated by Django 4.2.14 on 2024-08-01 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consvc_shepherd", "0009_revenue_overview_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placement", models.CharField()),
                ("revenue", models.IntegerField()),
                ("budget", models.IntegerField()),
                ("revenue_delta", models.IntegerField()),
                ("month", models.DateField()),
            ],
            options={
                "db_table": "revenue_overview",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(default="US", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AdsInventoryForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(default=datetime.date.today)),
                ("forecast", models.IntegerField(default=10)),
                (
                    "country",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.countries",
                    ),
                ),
            ],
        ),
    ]
