# Generated by Django 4.2.14 on 2024-09-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0009_alter_boostrproduct_campaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrdealproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boostrdealproduct',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boostrdealproduct',
            name='rate_type',
            field=models.CharField(choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('FF', 'Flat Fee')], null=True),
        ),
        migrations.AlterField(
            model_name='boostrdealproduct',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
