# Generated by Django 4.2.14 on 2024-08-02 16:24

from django.db import migrations


def create_countries(apps, schema_editor):
    Country = apps.get_model("consvc_shepherd", "Country")
    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).bulk_create(
        [
            Country(code="US", name="United States"),
            Country(code="CA", name="Canada"),
            Country(code="DE", name="Germany"),
            Country(code="ES", name="Spain"),
            Country(code="FR", name="France"),
            Country(code="GB", name="United Kingdom"),
            Country(code="IT", name="Italy"),
            Country(code="PL", name="Poland"),
            Country(code="AT", name="Austria"),
            Country(code="NL", name="Netherlands"),
            Country(code="LU", name="Luxembourg"),
            Country(code="CH", name="Switzerland"),
            Country(code="BE", name="Belgium"),
        ],
        ignore_conflicts=True,
    )


def remove_countries(apps, schema_editor):
    Country = apps.get_model("consvc_shepherd", "Country")
    db_alias = schema_editor.connection.alias

    Country.objects.using(db_alias).filter(
        code__in=[
            "US",
            "CA",
            "DE",
            "ES",
            "FR",
            "GB",
            "IT",
            "PL",
            "AT",
            "NL",
            "LU",
            "CH",
            "BE",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("consvc_shepherd", "0010_revenueoverview_countries_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Countries",
            new_name="Country",
        ),
        migrations.RunPython(
            create_countries,
            remove_countries,
        ),
    ]
