# Generated by Django 4.2.14 on 2024-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0010_boostrdealmediaplan_boostrdealmediaplanlineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="boostrdealproduct",
            name="quantity",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="boostrdealproduct",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name="boostrdealproduct",
            name="rate_type",
            field=models.CharField(
                choices=[("CPM", "CPM"), ("CPC", "CPC"), ("FF", "Flat Fee")], null=True
            ),
        ),
    ]
