# Generated by Django 4.2.14 on 2024-09-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0010_boostrproduct_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_ops_person", models.CharField()),
                ("notes", models.CharField()),
                ("kevel_flight_id", models.IntegerField()),
                ("net_spend", models.IntegerField()),
                ("impressions_sold", models.IntegerField()),
                ("net_ecpm", models.FloatField()),
                ("seller", models.CharField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.boostrdeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignOverviewSummary",
            fields=[],
            options={
                "verbose_name": "Campaign Summary",
                "verbose_name_plural": "Campaign Summaries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("consvc_shepherd.campaignoverview",),
        ),
    ]
