# Generated by Django 4.2.14 on 2024-09-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0010_boostrproduct_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boostrproduct",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("DE", "Germany"),
                    ("ES", "Spain"),
                    ("FR", "France"),
                    ("GB", "United Kingdom"),
                    ("IT", "Italy"),
                    ("PL", "Poland"),
                    ("AT", "Austria"),
                    ("NL", "Netherlands"),
                    ("LU", "Luxembourg"),
                    ("CH", "Switzerland"),
                    ("BE", "Belgium"),
                    ("SP", "Spain(SP)"),
                ],
                default="ES",
            ),
        ),
    ]
