# Generated by Django 4.2.14 on 2024-08-02 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "consvc_shepherd",
            "0010_revenueoverview_countries_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Countries",
            new_name="Country",
        ),
    ]
