# Generated by Django 4.2.14 on 2024-09-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0011_boostrsyncstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boostrsyncstatus",
            name="created_on",
        ),
    ]
