# Generated by Django 4.2.14 on 2024-08-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0011_adopscampaignmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrdeal',
            name='campaign_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consvc_shepherd.adopscampaignmanager'),
        ),
    ]
