# Generated by Django 4.2.14 on 2024-08-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0011_auto_20240802_1624'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
