# Generated by Django 4.2.15 on 2024-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0012_remove_boostrsyncstatus_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('flight_id', models.BigIntegerField()),
                ('campaign_id', models.BigIntegerField()),
                ('surface', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('clicks', models.IntegerField()),
                ('impressions', models.IntegerField()),
            ],
        ),
    ]
