# Generated by Django 4.2.16 on 2024-09-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0012_remove_boostrsyncstatus_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_ops_person", models.CharField()),
                ("notes", models.CharField()),
                ("kevel_flight_id", models.IntegerField()),
                ("net_spend", models.DecimalField(decimal_places=2, max_digits=12)),
                ("impressions_sold", models.IntegerField()),
                ("seller", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.boostrdeal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="CampaignSummary",
            fields=[
                ("deal_id", models.IntegerField(primary_key=True, serialize=False)),
                ("advertiser", models.CharField(max_length=255)),
                ("net_spend", models.FloatField()),
                ("impressions_sold", models.FloatField()),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaign Summaries",
                "db_table": "campaign_summary_view",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
            reverse_sql="DROP VIEW IF EXISTS campaign_summary_view;",
        ),
    ]
