# Generated by Django 4.2.14 on 2024-08-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contile', '0005_remove_partner_click_hosts_and_more'),
        ('consvc_shepherd', '0012_boostrdeal_campaign_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='KevelFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KevelAdvertiser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contile.advertiser',),
        ),
        migrations.CreateModel(
            name='KevelCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.PositiveIntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consvc_shepherd.kevelflight')),
            ],
        ),
        migrations.CreateModel(
            name='AdServerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_notes', models.TextField()),
                ('boostr_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consvc_shepherd.boostrdeal')),
            ],
        ),
    ]
