# Generated by Django 4.2.16 on 2024-09-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0012_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="net_ecpm",
        ),
    ]
