# Generated by Django 4.2.16 on 2024-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0013_remove_campaign_net_ecpm"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSummary",
            fields=[
                ("deal_id", models.IntegerField(primary_key=True, serialize=False)),
                ("advertiser", models.CharField(max_length=255)),
                ("net_spend", models.FloatField()),
                ("impressions_sold", models.FloatField()),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaign Summaries",
                "db_table": "campaign_summary_view",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
            reverse_sql="DROP VIEW IF EXISTS campaign_summary_view;",
        ),
    ]
