# Generated by Django 4.2.14 on 2024-08-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0013_kevelflight_keveladvertiser_kevelcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kevelcampaign',
            name='advertiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consvc_shepherd.keveladvertiser'),
            preserve_default=False,
        ),
    ]
