# Generated by Django 4.2.14 on 2024-08-03 00:36

from django.db import migrations


def create_ad_products(apps, schema_editor):
    AdProduct = apps.get_model("consvc_shepherd", "AdProduct")
    db_alias = schema_editor.connection.alias
    AdProduct.objects.using(db_alias).bulk_create(
        [
            AdProduct(name="Firefox New Tab Desktop"),
            AdProduct(name="Pocket Hits"),
            AdProduct(name="Pocket Syndication"),
            AdProduct(name="MDN (Direct Only)"),
            AdProduct(name="Firefox New Tab Mobile"),
            AdProduct(name="Firefox Tiles (Direct Only)"),
        ],
        ignore_conflicts=True,
    )


def remove_countries(apps, schema_editor):
    AdProduct = apps.get_model("consvc_shepherd", "AdProduct")
    db_alias = schema_editor.connection.alias
    ad_products_to_delete = [
        "Firefox New Tab Desktop",
        "Pocket Hits",
        "Pocket Syndication",
        "MDN (Direct Only)",
        "Firefox New Tab Mobile",
        "Firefox New Tab Mobile",
        "Firefox Tiles (Direct Only)",
    ]
    AdProduct.objects.using(db_alias).filter(name__in=ad_products_to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "consvc_shepherd",
            "0013_adproduct_alter_country_options_adsbudgetforecast_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_ad_products,
            remove_countries,
        )
    ]
