# Generated by Django 4.2.16 on 2024-09-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0014_alter_campaign_ad_ops_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boostrsyncstatus",
            name="synced_on",
            field=models.DateTimeField(),
        ),
    ]
