# Generated by Django 4.2.16 on 2024-09-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0014_alter_campaign_kevel_flight_id_deliveredcampaign"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deliveredcampaign",
            constraint=models.UniqueConstraint(
                fields=(
                    "submission_date",
                    "campaign_id",
                    "flight",
                    "country",
                    "provider",
                ),
                name="unique_delivered_campaign",
            ),
        ),
    ]
