# Generated by Django 4.2.16 on 2024-09-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0014_alter_campaign_ad_ops_person_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS campaign_summary_view;
            """,
            reverse_sql="""CREATE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser""",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="net_spend",
            field=models.IntegerField(),
        ),
        migrations.RunSQL(
            """
            CREATE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
            reverse_sql="DROP VIEW IF EXISTS campaign_summary_view;",
        ),
    ]
