# Generated by Django 4.2.14 on 2024-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0014_kevelcampaign_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='kevelflight',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kevelflight',
            name='name',
            field=models.CharField(default='Flight', max_length=100),
        ),
        migrations.AddField(
            model_name='kevelflight',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kevelflight',
            name='flight_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
