# Generated by Django 4.2.16 on 2024-09-18 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0014_alter_campaign_ad_ops_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="kevel_flight_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="DeliveredCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateField()),
                ("campaign_id", models.IntegerField()),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consvc_shepherd.campaign",
                        to_field="kevel_flight_id",
                    ),
                ),
                ("country", models.CharField()),
                ("provider", models.CharField()),
                ("clicks_delivered", models.IntegerField()),
                ("impressions_delivered", models.IntegerField()),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold,
                COALESCE(SUM(dc.impressions_delivered), 0) as impressions_delivered,
                COALESCE(SUM(dc.clicks_delivered), 0) as clicks_delivered
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            LEFT JOIN consvc_shepherd_deliveredcampaign dc
                ON c.kevel_flight_id = dc.flight_id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
            reverse_sql="""
            DROP VIEW campaign_summary_view;
            CREATE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
        ),
    ]
