# Generated by Django 4.2.16 on 2024-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0015_deliveredflight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostrsyncstatus',
            name='synced_on',
            field=models.DateTimeField(),
        ),
    ]
