# Generated by Django 4.2.16 on 2024-09-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0017_alter_boostrsyncstatus_synced_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["deal"],
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
    ]
