# Generated by Django 4.2.16 on 2024-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0018_fix_campaign_summary_view"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliveredflight",
            name="unique_delivered_flight",
        ),
        migrations.RemoveField(
            model_name="deliveredflight",
            name="country",
        ),
        migrations.AddConstraint(
            model_name="deliveredflight",
            constraint=models.UniqueConstraint(
                fields=("submission_date", "campaign_id", "flight_id", "provider"),
                name="unique_delivered_flight",
            ),
        ),
    ]
