# Generated by Django 4.2.16 on 2024-10-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "consvc_shepherd",
            "0019_remove_deliveredflight_unique_delivered_flight_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["deal"],
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
    ]
