# Generated by Django 4.2.16 on 2024-10-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consvc_shepherd",
            "0019_remove_deliveredflight_unique_delivered_flight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="boostrdealproduct",
            name="quantity",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name="boostrdealproduct",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name="boostrdealproduct",
            name="rate_type",
            field=models.CharField(
                choices=[("CPM", "CPM"), ("CPC", "CPC"), ("FF", "Flat Fee")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="boostrdealproduct",
            name="budget",
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
    ]
