# Generated by Django 4.2.16 on 2024-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0019_remove_deliveredflight_unique_delivered_flight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BQSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_on', models.DateTimeField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')])),
                ('message', models.CharField()),
            ],
        ),
    ]
