# Generated by Django 4.2.16 on 2024-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consvc_shepherd",
            "0019_remove_deliveredflight_unique_delivered_flight_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
            ],
        ),
    ]
