# Generated by Django 4.2.16 on 2024-10-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0020_alter_campaign_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='boostrdeal',
            name='advertiser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consvc_shepherd.advertiser'),
        ),
    ]
