# Generated by Django 4.2.16 on 2024-10-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0022_alter_boostrsyncstatus_options_and_more_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placement", models.CharField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                ("revenue", models.IntegerField()),
                ("inv_available", models.IntegerField()),
                ("inv_booked", models.IntegerField()),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventory",
                "db_table": "inventory_overview_view",
                "ordering": ["country"],
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE VIEW inventory_overview_view AS
                SELECT
                    ROW_NUMBER(
                ) OVER ( ORDER BY country) AS id,
                    bp.country AS country,
                    bp.campaign_type AS campaign_type,
                    SUM(
                        bdp.budget) AS revenue,
                    SUM(
                        bdp.quantity) * 4 AS inv_available,
                    SUM(
                        bdp.quantity) AS inv_booked,
                    CASE WHEN bp.full_name ~* 'New Tab Mobile' THEN
                        'Firefox Mobile'
                    WHEN bp.full_name ~* 'Firefox New Tab' THEN
                        'Firefox New Tab'
                    WHEN bp.full_name ~* 'Firefox \d+' THEN
                        'Firefox Desktop'
                    WHEN bp.full_name ~* 'Fakespot' THEN
                        'Fakespot'
                    WHEN bp.full_name ~* 'Pocket Hits Dedicated' THEN
                        'Pocket Hits (Dedicated)'
                    WHEN bp.full_name ~* 'Pocket Hits Standard' THEN
                        'Pocket Hits (Standard)'
                    WHEN bp.full_name ~* 'Pocket' THEN
                        'Pocket Hits'
                    WHEN bp.full_name ~* 'Tile' THEN
                        'Tiles'
                    ELSE
                        'Other'
                    END AS placement
                FROM
                    consvc_shepherd_boostrproduct bp
                    LEFT JOIN consvc_shepherd_boostrdealproduct bdp ON bp.id = bdp.boostr_product_id
                GROUP BY
                    placement,
                    bp.country,
                    campaign_type;
            """,
            reverse_sql="DROP VIEW IF EXISTS inventory_overview_view;",
        ),
    ]
