# Generated by Django 4.2.16 on 2024-10-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0022_alter_boostrsyncstatus_options_and_more_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('revenue', models.IntegerField(default=0)),
                ('inv_available', models.IntegerField(default=0)),
                ('inv_booked', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory_overview_view',
                'ordering': ['country'],
                'managed': False,
            },
        ),
    ]
