# Generated by Django 4.2.16 on 2024-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0022_alter_boostrsyncstatus_options_and_more_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredflight',
            name='campaign_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveredflight',
            name='flight_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
