# Generated by Django 4.2.16 on 2024-10-16 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0023_alter_deliveredflight_campaign_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="kevel_flight_id",
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kevel_flight_id", models.IntegerField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="consvc_shepherd.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight",
                "verbose_name_plural": "Flights",
            },
        ),
    ]
