# Generated by Django 4.2.16 on 2024-10-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0024_alter_deliveredflight_campaign_name_and_more"),
        ("consvc_shepherd", "0025_add_advertiser_id_to_campaign_summary_view"),
    ]

    operations = []
