# Generated by Django 4.2.16 on 2024-09-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0026_remove_campaign_kevel_flight_id_flight"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold,
                COALESCE(SUM(df.impressions_delivered), 0) AS impressions_delivered,
                COALESCE(SUM(df.clicks_delivered), 0) AS clicks_delivered
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            LEFT JOIN consvc_shepherd_flight f
                ON f.campaign_id = c.id
            LEFT JOIN consvc_shepherd_deliveredflight df
                ON f.kevel_flight_id = df.flight_id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser;
            """,
            reverse_sql="""
            DROP VIEW IF EXISTS campaign_summary_view;
            CREATE OR REPLACE VIEW campaign_summary_view AS
            SELECT
                d.id AS deal_id,
                d.advertiser AS advertiser,
                SUM(c.net_spend) AS net_spend,
                SUM(c.impressions_sold) AS impressions_sold,
                COALESCE(SUM(df.impressions_delivered), 0) as impressions_delivered,
                COALESCE(SUM(df.clicks_delivered), 0) as clicks_delivered
            FROM consvc_shepherd_boostrdeal d
            LEFT JOIN consvc_shepherd_campaign c
                ON c.deal_id = d.id
            LEFT JOIN consvc_shepherd_deliveredflight df
                ON c.kevel_flight_id = df.flight_id
            GROUP BY d.id, d.advertiser
            HAVING
                SUM(c.net_spend) IS NOT NULL
                AND SUM(c.impressions_sold) IS NOT NULL
            ORDER BY d.advertiser
            """,
        ),
    ]
