# Generated by Django 4.2.16 on 2024-10-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0028_fix_update_campaign_summary_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="boostrdeal",
            name="stage_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
