# Generated by Django 4.2.16 on 2024-10-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consvc_shepherd', '0029_boostrdeal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostrdealproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boostrdealproduct',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='boostrdealproduct',
            name='rate_type',
            field=models.CharField(choices=[('CPM', 'CPM'), ('CPC', 'CPC'), ('FF', 'Flat Fee')], null=True),
        ),
    ]
