# Generated by Django 4.2.16 on 2024-10-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consvc_shepherd", "0029_boostrdeal_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boostrdeal",
            name="stage",
            field=models.CharField(
                choices=[
                    ("Closed Won", "Closed Won"),
                    ("Verbal", "Verbal"),
                    ("Renewal", "Renewal"),
                ]
            ),
        ),
    ]
