services:
  db:
    tty: true
    restart: always
    image: postgres:14.0
    volumes:
      - db_volume:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  app:
    tty: true
    env_file:
      - .env
    image: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- python /app/manage.py migrate && python /app/manage.py runserver 0.0.0.0:7001 "
    links:
      - db
    volumes:
      - .:/app
    ports:
      - "7001:7001"
    depends_on:
      - db

  ad-ops-dashboard:
    image: node:alpine
    build:
      context: ./ad-ops-dashboard
    working_dir: /ad-ops-dashboard
    volumes:
      - ./ad-ops-dashboard:/ad-ops-dashboard
      - /ad-ops-dashboard/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - db
      - app

volumes:
  db_volume:
