services:
  db:
    tty: true
    restart: always
    image: postgres:14.0
    volumes:
      - db_volume:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  app:
    tty: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- pip install poetry && poetry install && poetry run pytest --cov --cov-report=term-missing --cov-fail-under=95 "
    volumes:
      - .:/app
    ports:
      - "7001:7001"
    depends_on:
      - db

  dashboard:
    tty: true
    build:
      context: ./dashboard
      dockerfile: ./Dockerfile
    command: npm run test
    ports:
      - "5173:5173"
    depends_on:
      - db
      - app

volumes:
  db_volume:
