version: "3"

services:
  db:
    restart: always
    image: postgres:14.0
    volumes:
      - db_volume:/var/lib/postgresql
    environment:
      POSTGRES_DB: consvc_shepherd
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - private_nw

  app:
    tty: true
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "python /app/manage.py migrate && python /app/manage.py runserver 0:8000"
    links:
      - db
    networks:
      - public_nw
      - private_nw
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_volume:
  node_modules_volume:
  ssl_volume:

networks:
  private_nw:
    internal: true
  public_nw:
