# Generated by Django 4.0.2 on 2022-05-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0002_partner_is_active_partner_last_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertiserurl",
            name="matching",
            field=models.BooleanField(
                choices=[(True, "exact"), (False, "prefix")], default=True
            ),
        ),
    ]
