# Generated by Django 4.0.4 on 2022-05-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0003_alter_advertiserurl_matching"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertiserurl",
            name="position",
        ),
    ]
