# Generated by Django 4.0.4 on 2022-10-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contile", "0004_remove_advertiserurl_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="click_hosts",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="impression_hosts",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="last_approved_by",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="last_updated_by",
        ),
    ]
