--
-- PostgreSQL database dump
--

-- Dumped from database version 14.0 (Debian 14.0-1.pgdg110+1)
-- Dumped by pg_dump version 14.0 (Debian 14.0-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_advertiser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_advertiser (
    id bigint NOT NULL,
    name character varying NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL
);


ALTER TABLE public.consvc_shepherd_advertiser OWNER TO postgres;

--
-- Name: consvc_shepherd_boostrdeal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_boostrdeal (
    id bigint NOT NULL,
    boostr_id integer NOT NULL,
    name character varying NOT NULL,
    advertiser character varying NOT NULL,
    currency character varying NOT NULL,
    amount integer NOT NULL,
    sales_representatives character varying NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    advertiser_id_id bigint
);


ALTER TABLE public.consvc_shepherd_boostrdeal OWNER TO postgres;

--
-- Name: consvc_shepherd_campaign; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_campaign (
    id bigint NOT NULL,
    ad_ops_person character varying,
    notes character varying,
    net_spend integer NOT NULL,
    impressions_sold integer NOT NULL,
    seller character varying NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    deal_id bigint NOT NULL
);


ALTER TABLE public.consvc_shepherd_campaign OWNER TO postgres;

--
-- Name: consvc_shepherd_deliveredflight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_deliveredflight (
    id bigint NOT NULL,
    submission_date date NOT NULL,
    campaign_id integer NOT NULL,
    campaign_name character varying,
    flight_id integer NOT NULL,
    flight_name character varying,
    provider character varying,
    clicks_delivered integer NOT NULL,
    impressions_delivered integer NOT NULL
);


ALTER TABLE public.consvc_shepherd_deliveredflight OWNER TO postgres;

--
-- Name: consvc_shepherd_flight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_flight (
    id bigint NOT NULL,
    kevel_flight_id integer,
    campaign_id bigint
);


ALTER TABLE public.consvc_shepherd_flight OWNER TO postgres;

--
-- Name: campaign_summary_view; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.campaign_summary_view AS
 SELECT d.id AS deal_id,
    d.advertiser,
    sum(c.net_spend) AS net_spend,
    sum(c.impressions_sold) AS impressions_sold,
    COALESCE(sum(df.impressions_delivered), (0)::bigint) AS impressions_delivered,
    COALESCE(sum(df.clicks_delivered), (0)::bigint) AS clicks_delivered,
    a.id AS advertiser_id_id
   FROM ((((public.consvc_shepherd_boostrdeal d
     LEFT JOIN public.consvc_shepherd_campaign c ON ((c.deal_id = d.id)))
     LEFT JOIN public.consvc_shepherd_flight f ON ((f.campaign_id = c.id)))
     LEFT JOIN public.consvc_shepherd_deliveredflight df ON ((f.kevel_flight_id = df.flight_id)))
     LEFT JOIN public.consvc_shepherd_advertiser a ON ((d.advertiser_id_id = a.id)))
  GROUP BY d.id, d.advertiser, a.id
 HAVING ((sum(c.net_spend) IS NOT NULL) AND (sum(c.impressions_sold) IS NOT NULL))
  ORDER BY d.advertiser;


ALTER TABLE public.campaign_summary_view OWNER TO postgres;

--
-- Name: consvc_shepherd_advertiser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_advertiser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_advertiser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_allocationsetting; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_allocationsetting (
    id bigint NOT NULL,
    "position" integer NOT NULL
);


ALTER TABLE public.consvc_shepherd_allocationsetting OWNER TO postgres;

--
-- Name: consvc_shepherd_allocationsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_allocationsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_allocationsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_allocationsettingssnapshot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_allocationsettingssnapshot (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    json_settings jsonb,
    created_on timestamp with time zone NOT NULL,
    launched_date timestamp with time zone,
    created_by_id integer,
    launched_by_id integer
);


ALTER TABLE public.consvc_shepherd_allocationsettingssnapshot OWNER TO postgres;

--
-- Name: consvc_shepherd_allocationsettingssnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_allocationsettingssnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_allocationsettingssnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_boostrdeal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_boostrdeal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_boostrdeal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_boostrdealproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_boostrdealproduct (
    id bigint NOT NULL,
    budget integer NOT NULL,
    month character varying NOT NULL,
    boostr_deal_id bigint NOT NULL,
    boostr_product_id bigint NOT NULL
);


ALTER TABLE public.consvc_shepherd_boostrdealproduct OWNER TO postgres;

--
-- Name: consvc_shepherd_boostrdealproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_boostrdealproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_boostrdealproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_boostrproduct; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_boostrproduct (
    id bigint NOT NULL,
    boostr_id integer NOT NULL,
    full_name character varying NOT NULL,
    campaign_type character varying NOT NULL,
    created_on timestamp with time zone NOT NULL,
    updated_on timestamp with time zone NOT NULL,
    country character varying NOT NULL
);


ALTER TABLE public.consvc_shepherd_boostrproduct OWNER TO postgres;

--
-- Name: consvc_shepherd_boostrproduct_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_boostrproduct ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_boostrproduct_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_boostrsyncstatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_boostrsyncstatus (
    id bigint NOT NULL,
    synced_on timestamp with time zone NOT NULL,
    status character varying NOT NULL,
    message character varying NOT NULL
);


ALTER TABLE public.consvc_shepherd_boostrsyncstatus OWNER TO postgres;

--
-- Name: consvc_shepherd_boostrsyncstatus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_boostrsyncstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_boostrsyncstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_bqsyncstatus; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_bqsyncstatus (
    id bigint NOT NULL,
    synced_on timestamp with time zone NOT NULL,
    status character varying NOT NULL,
    message character varying NOT NULL,
    query_date timestamp with time zone
);


ALTER TABLE public.consvc_shepherd_bqsyncstatus OWNER TO postgres;

--
-- Name: consvc_shepherd_bqsyncstatus_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_bqsyncstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_bqsyncstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_campaign_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_campaign ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_campaign_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_deliveredflight_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_deliveredflight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_deliveredflight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_flight_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_flight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_flight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_partnerallocation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_partnerallocation (
    id bigint NOT NULL,
    percentage integer NOT NULL,
    allocation_position_id bigint NOT NULL,
    partner_id bigint
);


ALTER TABLE public.consvc_shepherd_partnerallocation OWNER TO postgres;

--
-- Name: consvc_shepherd_partnerallocation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_partnerallocation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_partnerallocation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consvc_shepherd_settingssnapshot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.consvc_shepherd_settingssnapshot (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    json_settings jsonb,
    created_on timestamp with time zone NOT NULL,
    launched_date timestamp with time zone,
    created_by_id integer,
    launched_by_id integer,
    settings_type_id bigint
);


ALTER TABLE public.consvc_shepherd_settingssnapshot OWNER TO postgres;

--
-- Name: consvc_shepherd_settingssnapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.consvc_shepherd_settingssnapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consvc_shepherd_settingssnapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contile_advertiser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contile_advertiser (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    partner_id bigint NOT NULL
);


ALTER TABLE public.contile_advertiser OWNER TO postgres;

--
-- Name: contile_advertiser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contile_advertiser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contile_advertiser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contile_advertiserurl; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contile_advertiserurl (
    id bigint NOT NULL,
    geo character varying(2) NOT NULL,
    domain character varying(255) NOT NULL,
    path character varying(128) NOT NULL,
    matching boolean NOT NULL,
    advertiser_id bigint NOT NULL
);


ALTER TABLE public.contile_advertiserurl OWNER TO postgres;

--
-- Name: contile_advertiserurl_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contile_advertiserurl ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contile_advertiserurl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contile_partner; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contile_partner (
    id bigint NOT NULL,
    name character varying(128) NOT NULL
);


ALTER TABLE public.contile_partner OWNER TO postgres;

--
-- Name: contile_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contile_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contile_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: consvc_shepherd_advertiser consvc_shepherd_advertiser_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_advertiser
    ADD CONSTRAINT consvc_shepherd_advertiser_name_key UNIQUE (name);


--
-- Name: consvc_shepherd_advertiser consvc_shepherd_advertiser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_advertiser
    ADD CONSTRAINT consvc_shepherd_advertiser_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_allocationsetting consvc_shepherd_allocationsetting_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_allocationsetting
    ADD CONSTRAINT consvc_shepherd_allocationsetting_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_allocationsetting consvc_shepherd_allocationsetting_position_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_allocationsetting
    ADD CONSTRAINT consvc_shepherd_allocationsetting_position_key UNIQUE ("position");


--
-- Name: consvc_shepherd_allocationsettingssnapshot consvc_shepherd_allocationsettingssnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_allocationsettingssnapshot
    ADD CONSTRAINT consvc_shepherd_allocationsettingssnapshot_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_boostrdeal consvc_shepherd_boostrdeal_boostr_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdeal
    ADD CONSTRAINT consvc_shepherd_boostrdeal_boostr_id_key UNIQUE (boostr_id);


--
-- Name: consvc_shepherd_boostrdeal consvc_shepherd_boostrdeal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdeal
    ADD CONSTRAINT consvc_shepherd_boostrdeal_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_boostrdealproduct consvc_shepherd_boostrdealproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdealproduct
    ADD CONSTRAINT consvc_shepherd_boostrdealproduct_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_boostrproduct consvc_shepherd_boostrproduct_boostr_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrproduct
    ADD CONSTRAINT consvc_shepherd_boostrproduct_boostr_id_key UNIQUE (boostr_id);


--
-- Name: consvc_shepherd_boostrproduct consvc_shepherd_boostrproduct_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrproduct
    ADD CONSTRAINT consvc_shepherd_boostrproduct_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_boostrsyncstatus consvc_shepherd_boostrsyncstatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrsyncstatus
    ADD CONSTRAINT consvc_shepherd_boostrsyncstatus_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_bqsyncstatus consvc_shepherd_bqsyncstatus_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_bqsyncstatus
    ADD CONSTRAINT consvc_shepherd_bqsyncstatus_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_campaign consvc_shepherd_campaign_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_campaign
    ADD CONSTRAINT consvc_shepherd_campaign_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_deliveredflight consvc_shepherd_deliveredflight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_deliveredflight
    ADD CONSTRAINT consvc_shepherd_deliveredflight_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_flight consvc_shepherd_flight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_flight
    ADD CONSTRAINT consvc_shepherd_flight_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_partnerallocation consvc_shepherd_partnerallocation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_partnerallocation
    ADD CONSTRAINT consvc_shepherd_partnerallocation_pkey PRIMARY KEY (id);


--
-- Name: consvc_shepherd_settingssnapshot consvc_shepherd_settingssnapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_settingssnapshot
    ADD CONSTRAINT consvc_shepherd_settingssnapshot_pkey PRIMARY KEY (id);


--
-- Name: contile_advertiser contile_advertiser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contile_advertiser
    ADD CONSTRAINT contile_advertiser_pkey PRIMARY KEY (id);


--
-- Name: contile_advertiserurl contile_advertiserurl_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contile_advertiserurl
    ADD CONSTRAINT contile_advertiserurl_pkey PRIMARY KEY (id);


--
-- Name: contile_partner contile_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contile_partner
    ADD CONSTRAINT contile_partner_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: consvc_shepherd_deliveredflight unique_delivered_flight; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_deliveredflight
    ADD CONSTRAINT unique_delivered_flight UNIQUE (submission_date, campaign_id, flight_id, provider);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: consvc_shepherd_advertiser_name_1b1123f1_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_advertiser_name_1b1123f1_like ON public.consvc_shepherd_advertiser USING btree (name varchar_pattern_ops);


--
-- Name: consvc_shepherd_allocation_created_by_id_d5c4b12f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_allocation_created_by_id_d5c4b12f ON public.consvc_shepherd_allocationsettingssnapshot USING btree (created_by_id);


--
-- Name: consvc_shepherd_allocation_launched_by_id_a344d2ea; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_allocation_launched_by_id_a344d2ea ON public.consvc_shepherd_allocationsettingssnapshot USING btree (launched_by_id);


--
-- Name: consvc_shepherd_boostrdeal_advertiser_id_id_de2c96e0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_boostrdeal_advertiser_id_id_de2c96e0 ON public.consvc_shepherd_boostrdeal USING btree (advertiser_id_id);


--
-- Name: consvc_shepherd_boostrdealproduct_boostr_deal_id_65953dfe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_boostrdealproduct_boostr_deal_id_65953dfe ON public.consvc_shepherd_boostrdealproduct USING btree (boostr_deal_id);


--
-- Name: consvc_shepherd_boostrdealproduct_boostr_product_id_230269c0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_boostrdealproduct_boostr_product_id_230269c0 ON public.consvc_shepherd_boostrdealproduct USING btree (boostr_product_id);


--
-- Name: consvc_shepherd_campaign_deal_id_4fd2c760; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_campaign_deal_id_4fd2c760 ON public.consvc_shepherd_campaign USING btree (deal_id);


--
-- Name: consvc_shepherd_flight_campaign_id_e2dea6fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_flight_campaign_id_e2dea6fb ON public.consvc_shepherd_flight USING btree (campaign_id);


--
-- Name: consvc_shepherd_partnerall_allocationPosition_id_14cf58ad; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "consvc_shepherd_partnerall_allocationPosition_id_14cf58ad" ON public.consvc_shepherd_partnerallocation USING btree (allocation_position_id);


--
-- Name: consvc_shepherd_partnerallocation_partner_id_4ef9c424; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_partnerallocation_partner_id_4ef9c424 ON public.consvc_shepherd_partnerallocation USING btree (partner_id);


--
-- Name: consvc_shepherd_settingssnapshot_created_by_id_99162aa5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_settingssnapshot_created_by_id_99162aa5 ON public.consvc_shepherd_settingssnapshot USING btree (created_by_id);


--
-- Name: consvc_shepherd_settingssnapshot_launched_by_id_eb4f2f6d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_settingssnapshot_launched_by_id_eb4f2f6d ON public.consvc_shepherd_settingssnapshot USING btree (launched_by_id);


--
-- Name: consvc_shepherd_settingssnapshot_settings_type_id_896ec79b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX consvc_shepherd_settingssnapshot_settings_type_id_896ec79b ON public.consvc_shepherd_settingssnapshot USING btree (settings_type_id);


--
-- Name: contile_advertiser_partner_id_5f6ea237; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contile_advertiser_partner_id_5f6ea237 ON public.contile_advertiser USING btree (partner_id);


--
-- Name: contile_advertiserurl_advertiser_id_115ff070; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX contile_advertiserurl_advertiser_id_115ff070 ON public.contile_advertiserurl USING btree (advertiser_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_allocationsettingssnapshot consvc_shepherd_allo_created_by_id_d5c4b12f_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_allocationsettingssnapshot
    ADD CONSTRAINT consvc_shepherd_allo_created_by_id_d5c4b12f_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_allocationsettingssnapshot consvc_shepherd_allo_launched_by_id_a344d2ea_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_allocationsettingssnapshot
    ADD CONSTRAINT consvc_shepherd_allo_launched_by_id_a344d2ea_fk_auth_user FOREIGN KEY (launched_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_boostrdeal consvc_shepherd_boos_advertiser_id_id_de2c96e0_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdeal
    ADD CONSTRAINT consvc_shepherd_boos_advertiser_id_id_de2c96e0_fk_consvc_sh FOREIGN KEY (advertiser_id_id) REFERENCES public.consvc_shepherd_advertiser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_boostrdealproduct consvc_shepherd_boos_boostr_deal_id_65953dfe_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdealproduct
    ADD CONSTRAINT consvc_shepherd_boos_boostr_deal_id_65953dfe_fk_consvc_sh FOREIGN KEY (boostr_deal_id) REFERENCES public.consvc_shepherd_boostrdeal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_boostrdealproduct consvc_shepherd_boos_boostr_product_id_230269c0_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_boostrdealproduct
    ADD CONSTRAINT consvc_shepherd_boos_boostr_product_id_230269c0_fk_consvc_sh FOREIGN KEY (boostr_product_id) REFERENCES public.consvc_shepherd_boostrproduct(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_campaign consvc_shepherd_camp_deal_id_4fd2c760_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_campaign
    ADD CONSTRAINT consvc_shepherd_camp_deal_id_4fd2c760_fk_consvc_sh FOREIGN KEY (deal_id) REFERENCES public.consvc_shepherd_boostrdeal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_flight consvc_shepherd_flig_campaign_id_e2dea6fb_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_flight
    ADD CONSTRAINT consvc_shepherd_flig_campaign_id_e2dea6fb_fk_consvc_sh FOREIGN KEY (campaign_id) REFERENCES public.consvc_shepherd_campaign(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_partnerallocation consvc_shepherd_part_allocation_position__8c71a610_fk_consvc_sh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_partnerallocation
    ADD CONSTRAINT consvc_shepherd_part_allocation_position__8c71a610_fk_consvc_sh FOREIGN KEY (allocation_position_id) REFERENCES public.consvc_shepherd_allocationsetting(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_partnerallocation consvc_shepherd_part_partner_id_4ef9c424_fk_contile_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_partnerallocation
    ADD CONSTRAINT consvc_shepherd_part_partner_id_4ef9c424_fk_contile_p FOREIGN KEY (partner_id) REFERENCES public.contile_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_settingssnapshot consvc_shepherd_sett_created_by_id_99162aa5_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_settingssnapshot
    ADD CONSTRAINT consvc_shepherd_sett_created_by_id_99162aa5_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_settingssnapshot consvc_shepherd_sett_launched_by_id_eb4f2f6d_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_settingssnapshot
    ADD CONSTRAINT consvc_shepherd_sett_launched_by_id_eb4f2f6d_fk_auth_user FOREIGN KEY (launched_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: consvc_shepherd_settingssnapshot consvc_shepherd_sett_settings_type_id_896ec79b_fk_contile_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.consvc_shepherd_settingssnapshot
    ADD CONSTRAINT consvc_shepherd_sett_settings_type_id_896ec79b_fk_contile_p FOREIGN KEY (settings_type_id) REFERENCES public.contile_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contile_advertiser contile_advertiser_partner_id_5f6ea237_fk_contile_partner_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contile_advertiser
    ADD CONSTRAINT contile_advertiser_partner_id_5f6ea237_fk_contile_partner_id FOREIGN KEY (partner_id) REFERENCES public.contile_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: contile_advertiserurl contile_advertiserur_advertiser_id_115ff070_fk_contile_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contile_advertiserurl
    ADD CONSTRAINT contile_advertiserur_advertiser_id_115ff070_fk_contile_a FOREIGN KEY (advertiser_id) REFERENCES public.contile_advertiser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

